version: "3.3"
services:
  dbbountydash:
    image: mariadb
    restart: always
    volumes:
      - dbbountydash-volume:/var/lib/mysql
      - ./base.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bugbounty
      MYSQL_USER: bugbounty
      MYSQL_PASSWORD: 29ani6ibuKzyayWvCrLBQuTXp674R5hy

  appdountydash:
    build: .
    command: /usr/sbin/apache2ctl -D FOREGROUND
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/Bounty-Dashboard/
    depends_on:
      - dbbountydash
    links:
      - dbbountydash

volumes:
  dbbountydash-volume: