version: "3.8"
    
networks:
  symfony-network:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.19
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - symfony-network
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_USER}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}

  symfony:
    container_name: symfony
    command: /usr/sbin/apache2ctl -D FOREGROUND
    build:
      context: .
      dockerfile: ./docker/symfony/Dockerfile
    links:
      - mariadb
    # Database must be ready before running this searvice
    depends_on:
      - mariadb
    networks:
      - symfony-network
    ports:
      - "80:80"